### ISSUE TITLE
structure for one project per artist?

### ISSUE THREAD

**Issue by lmccart** [uclaconditional/art-software#15]

**Comment by REAS** [comment]
I think we had some great thoughts on this topic on the Thursday meeting in favor of supporting multiple projects for each artist:

- artists who make many different kinds of things
- artists with long careers, it would be interesting to "see" how the works changed over a long period of time

The discussion comes back around to the use of this project. Is it a massive data set containing everything to know about an artists? Is it an index? It's likely somewhere between...
